[package]
name = "awsync"
version = "0.1.0"
authors = ["Ilia Konnov <iliakonnov@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
tokio = {version="0.2", features=["full"]}
async-trait = "0.1.42"
time = {version="0.2.23", default-features=false, features=["std", "serde"] }
os_str_bytes = "2.4"
walkdir = "2.3"
tar = "0.4"
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
sha2 = "0.9.2"
base64 = "0.13.0"
md-5 = "0.9.1"
heed = {version="0.10.6", default-features=false, features=["mdbx", "serde-bincode"]}
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.15"