[package]
name = "awsync"
version = "0.1.0"
authors = ["Ilia Konnov <iliakonnov@gmail.com>"]
edition = "2018"

[lib]
name = "awsync_lib"
path = "src/lib.rs"

[[bin]]
name = "awsync"
path = "src/main.rs"

[dependencies]
structopt = "0.3.21"
once_cell = "1.8.0"
num_enum = "0.5.1"
snafu = { version = "0.6.10", default-features = false, features = ["std", "unstable-backtraces-impl-std"] }
futures = "0.3.15"
tokio = { version = "1.7.1", features = ["full"] }
tokio-util = { version = "0.6.7", features = ["codec", "compat"] }
bytes = "1.0.1"
async-trait = "0.1.50"
pin-project-lite = "0.2.7"
static_assertions = "1.1.0"
time = { version = "0.2.27", default-features = false, features = ["std", "serde"] }
os_str_bytes = "3.1.0"
hex = "0.4.3"
walkdir = "2.3.2"
fs2 = "0.4.3"
rusqlite = "0.25.3"
either = "1.6.1"
digest = "0.9.0"
sha2 = "0.9.5"
base64 = "0.13.0"
md-5 = "0.9.1"
serde = { version = "1.0.126", features = [ "unstable" ] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
