[package]
name = "awsync"
version = "0.1.0"
authors = ["Ilia Konnov <iliakonnov@gmail.com>"]
edition = "2018"

[lib]
name = "awsync_lib"
path = "src/lib.rs"

[[bin]]
name = "awsync"
path = "src/main.rs"

[dependencies]
structopt = "0.3.21"
once_cell = "1.7.2"
num_enum = "0.5.1"
snafu = { version = "0.6.10", default-features = false, features = ["std", "unstable-backtraces-impl-std"] }
futures = "0.3.14"
tokio = { version = "1.5.0", features = ["full"] }
tokio-util = { version = "0.6.6", features = ["codec", "compat"] }
bytes = "1.0.1"
async-trait = "0.1.50"
pin-project-lite = "0.2.6"
static_assertions = "1.1.0"
time = { version = "0.2.26", default-features = false, features = ["std", "serde"] }
os_str_bytes = "3.0.0"
hex = "0.4.3"
walkdir = "2.3.2"
fs2 = "0.4.3"
rusoto_core = "0.46.0"
rusoto_s3 = { version = "0.46.0", features = ["serialize_structs"] }
rusqlite = "0.25.1"
either = "1.6.1"
digest = "0.9.0"
sha2 = "0.9.3"
base64 = "0.13.0"
md-5 = "0.9.1"
serde = "1.0.125"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
