[package]
name = "awsync"
version = "0.1.0"
authors = ["Ilia Konnov <iliakonnov@gmail.com>"]
edition = "2018"

[lib]
name = "awsync_lib"
path = "src/lib.rs"

[[bin]]
name = "awsync"
path = "src/main.rs"

[dependencies]
structopt = "0.3.21"
snafu = { version = "0.6.10", default-features = false, features = ["std", "unstable-backtraces-impl-std"] }
tokio = { version = "1.2", features = ["full"] }
async-trait = "0.1.42"
pin-project-lite = "0.2.4"
time = { version = "0.2.25", default-features = false, features = ["std", "serde"] }
os_str_bytes = "2.4.0"
walkdir = "2.3.1"
fs2 = "0.4.3"
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
either = "1.6.1"
sha2 = "0.9.3"
base64 = "0.13.0"
md-5 = "0.9.1"
static_assertions = "1.1.0"
serde = "1.0.123"
serde_json = "1.0.62"
serde_yaml = "0.8.17"
