name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "0 4 * * SAT"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install latest rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Prepare for running tests
        run: mkdir logs && ./generate_tests.sh
      - name: Run tests
        run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "clippy"
      - run: cargo clippy --tests -- -Dwarnings
